[tool.poetry]
name = "delica"
version = "0.1.0"
description = ""
authors = ["Isaac Flores-Huerta <isaac@flores-huerta.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
